/* Create Tables */

CREATE TABLE "BOOK"
("ISBN" CHAR(10)  NOT NULL,
"Title" VARCHAR(30) NOT NULL,
"FirstName" VARCHAR(15),
"MiddleName" VARCHAR(15),
"LastName" VARCHAR(15) NOT NULL,
"Price" DOUBLE NOT NULL,
"Publisher" VARCHAR(30),
"Category" VARCHAR(15),
"Year" INTEGER,
"Quantity" INTEGER,
"QuantitySold" INTEGER,
PRIMARY KEY ("ISBN", "FirstName", "LastName"));

CREATE TABLE "CART"
("BookTitle" VARCHAR(30) NOT NULL,
"AccountID" INTEGER NOT NULL, 
PRIMARY KEY ("BookTitle", "AccountID"));

CREATE TABLE "CUSTOMER"
("AccountID" INTEGER PRIMARY KEY  NOT NULL, 
"FirstName" VARCHAR(15) NOT NULL,
"LastName" VARCHAR(15) NOT NULL,
"Email" VARCHAR(30) NOT NULL);

CREATE TABLE "DISPLAYED_IN"
("WishlistID" INTEGER NOT NULL, 
"ISBN" CHAR(10) NOT NULL, 
PRIMARY KEY ("WishlistID", "ISBN"));

CREATE TABLE "HELD_IN" 
("RecommendID" INTEGER NOT NULL, 
"ISBN" CHAR(10) NOT NULL,
PRIMARY KEY ("RecommendID", "ISBN"));

CREATE TABLE "RECOMMENDED_LIST" 
("RecomID" INTEGER PRIMARY KEY  NOT NULL, 
"AccountID" INTEGER NOT NULL);

CREATE TABLE "TRANS" 
("TransID" INTEGER PRIMARY KEY  NOT NULL, 
"AccountID" INTEGER NOT NULL,
"Amount" DOUBLE NOT NULL,
"Date" DATETIME, 
"Downloadable" BOOL,
"Shipping" BOOL,
"PayMethod" VARCHAR(15));

CREATE TABLE "WISHLIST" 
("WishlistID" INTEGER PRIMARY KEY NOT NULL,
"AccountID" INTEGER NOT NULL, 
"WishlistName" VARCHAR(15));

CREATE TABLE "CONTAINED_IN" 
("ISBN" CHAR(10) NOT NULL, 
"TransID" INTEGER NOT NULL,
PRIMARY KEY ("ISBN", "TransID"));


/* Create Indexes */

CREATE INDEX Book_Quantity_Index
ON BOOK(Quantity);

CREATE INDEX Book_Year_Index
ON BOOK(Year);
